// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  var init, makeItem, search, totallicks;

  init = function() {
    var input;
    window.searchstatus = false;
    $("input:text:visible:first").focus();
    totallicks();
    $('.logo').on("click", function() {
      return chrome.tabs.create({
        url: "http://totallicks.com"
      });
    });
    $('#results').on("click", "li", function() {
      var path;
      path = $(this).find("a").attr('href');
      return chrome.tabs.create({
        url: path
      });
    });
    $('#features').on("click", "li", function() {
      var path;
      path = $(this).find("a").attr('href');
      return chrome.tabs.create({
        url: path
      });
    });
    $(document).on("mouseover", "#results li", function() {
      window.indexLine = $(this).data("index");
      return $("#results li:nth-child(" + window.indexLine + ")").addClass("over");
    });
    $(document).on("mouseout", "#results li", function() {
      return $("#results li:nth-child(" + window.indexLine + ")").removeClass("over");
    });
    input = $("input[type=text]");
    Mousetrap.bind("enter", function() {
      var path;
      if (window.indexLine >= 1) {
        path = $('.over').find("a").attr('href');
        return chrome.tabs.create({
          url: path
        });
      } else {
        if ($('#search').val().length > 1 && window.searchstatus === false) {
          return search();
        }
      }
    });
    Mousetrap.bind("down", function(e) {
      if (window.indexLine === 1) {
        $("#results li:nth-child(" + window.indexLine + ")").removeClass("over");
      }
      if (window.indexLine >= 1 && window.indexLine <= $('#results li').length - 1) {
        $("#results li:nth-child(" + window.indexLine + ")").removeClass("over");
        ++window.indexLine;
        $("#results li:nth-child(" + window.indexLine + ")").addClass("over");
      }
      if (e.target === input[0]) {
        input.blur();
        window.indexLine = 1;
        return $("#results li:nth-child(" + window.indexLine + ")").addClass("over");
      }
    });
    Mousetrap.bind("up", function() {
      if (window.indexLine >= 1) {
        $("#results li:nth-child(" + window.indexLine + ")").removeClass("over");
        --window.indexLine;
        $("#results li:nth-child(" + window.indexLine + ")").addClass("over");
      }
      if (window.indexLine === 0) {
        return input.focus();
      }
    });
    return $(document).on("click", "#dismiss", function() {
      $('.help').remove();
      return localStorage.help = false;
    });
  };

  search = function(tabname) {
    var opts, results, spinerTarget, spinner;
    if (tabname == null) {
      tabname = $("#search").val();
    }
    window.searchstatus = true;
    $('#features').hide();
    opts = {
      lines: 9,
      length: 18,
      width: 11,
      radius: 23,
      corners: 1,
      rotate: 0,
      direction: 1,
      color: "#000",
      speed: 1,
      trail: 58,
      shadow: false,
      hwaccel: false,
      className: "spinner",
      zIndex: 2e9,
      top: "auto",
      left: "auto"
    };
    spinerTarget = $('#spinner');
    results = $('#results li');
    $('#results').empty();
    $('.help').remove();
    if (results.length > 0) {
      results.remove();
    }
    if (tabname === "") {
      $('#results').append("<div class='message warning'>Ups. Write something please.</div>");
      $("input[type=text]").focus();
      return window.searchstatus = false;
    } else {
      spinner = new Spinner(opts).spin();
      spinerTarget.append(spinner.el);
      return $.ajax({
        url: "http://totallicks.com/songbook/search/",
        type: "GET",
        dataType: "json",
        data: {
          tab: tabname
        },
        success: function(data) {
          var count, help, item, _i, _len, _ref;
          spinner.stop();
          if (data["success"] && data["feed"].length > 0) {
            count = 1;
            _ref = data["feed"];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              item = _ref[_i];
              makeItem(item, count);
              ++count;
            }
            $('#results li:first-child').addClass("over");
            $("input[type=text]").blur();
            window.indexLine = 1;
            help = localStorage.getItem('help');
            if (help === "true") {
              $("<div class='help'>Use <span class='kbd'>↑</span> and <span class='kbd'>↓</span> to navigate, <span class='kbd'>enter</span> to view tabs <a href='#' id='dismiss' class='dismiss' title='Hide this notice forever' rel='nofollow'>&#10006;</a></div> ").insertBefore('#results');
            }
          } else {
            $('#results').append("<div class='message warning'>No Results.</div>");
            window.indexLine = 0;
          }
          return window.searchstatus = false;
        }
      });
    }
  };

  totallicks = function() {
    var handler, input;
    input = $("input[type=text]");
    handler = function(e) {
      if (e.keyCode === 38 || e.keyCode === 40) {
        return e.preventDefault();
      }
    };
    input.keydown(handler);
    input.keypress(handler);
    input.keypress(function(e) {});
    return $("input[type=submit]").click(function() {
      return search();
    });
  };

  makeItem = function(item, count) {
    if (item['artist'] !== null && item['artist'] !== "") {
      return $('#results').append(("<li class='item' data-index='" + count + "'> <a href='") + item['path'] + "'>&#9658; " + item['artist'] + " - " + item['name'] + "</a></li>");
    } else {
      return $('#results').append(("<li class='item' data-index='" + count + "'> <a href='") + item['path'] + "'>&#9658; " + item['name'] + "</a></li>");
    }
  };

  $(document).ready(function() {
    var help;
    help = localStorage.getItem('help');
    if (!help) {
      localStorage.help = true;
    }
    window.indexLine = 0;
    setTimeout((function() {
      return $("input[type=text]").focus();
    }), 500);
    return init();
  });

}).call(this);
